# Generated by Django 6.0.7 on 2026-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_no', models.IntegerField(max_length=50)),
                ('form', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
            ],
        ),
    ]
